/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MacrosRouteImport } from './routes/macros'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as IndexRouteImport } from './routes/index'

const MacrosRoute = MacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRoute
  '/macros': typeof MacrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRoute
  '/macros': typeof MacrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRoute
  '/macros': typeof MacrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inventario' | '/macros'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventario' | '/macros'
  id: '__root__' | '/' | '/inventario' | '/macros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventarioRoute: typeof InventarioRoute
  MacrosRoute: typeof MacrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/macros': {
      id: '/macros'
      path: '/macros'
      fullPath: '/macros'
      preLoaderRoute: typeof MacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventarioRoute: InventarioRoute,
  MacrosRoute: MacrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
