// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client using the same publishable key as the browser.
// Do not use service_role or secret keys here.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseClientEnv } from './env';

function createSupabaseServerClient() {
  const { url, publishableKey } = getSupabaseClientEnv();

  return createClient<Database>(url, publishableKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseServer: ReturnType<typeof createSupabaseServerClient> | undefined;

// Server-side Supabase client with the publishable key. RLS still applies.
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseServerClient>, {
  get(_, prop, receiver) {
    if (!_supabaseServer) _supabaseServer = createSupabaseServerClient();
    return Reflect.get(_supabaseServer, prop, receiver);
  },
});
